import './room'
import './user'
import './game'
import './match'
import './opsWeb'
import './action'
import './system'
import './fortune'
import './infraWeb'
import './userOpsWeb'
import './announcement'
import './runtimeSettingsWeb'
import './matchDomainEventWeb'

export { default as default } from './instance'
